spring:
  application:
    name: currency-conversion-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8200
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost