spring:
  application:
    name: currency-conversion-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
server:
  port: 8200
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka