spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:db
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
server:
  port: 8100
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
