spring:
  application:
    name: currency-exchange-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:db
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  sleuth:
    sampler:
      probability: 1.0
server:
  port: 8100
eureka:
  client:
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
resilience4j:
  retry:
    instances:
      #default:
        #failureRateThreshold: 90
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  rateLimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
